#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

if [[ $(xrandr -q | grep "HDMI-1 connected") ]];
then
      xrandr --output HDMI-1 --mode 1680x1050  --primary \
             --output eDP-1  --mode 1366x768 --left-of HDMI-1 

      bspc monitor HDMI-1 -d c d 
      bspc monitor eDP-1 -d a b   

else
    xrandr --output eDP-1 --mode 1366x768 --primary \
           --output HDMI-1 --off

    bspc monitor eDP-1 -d a b c d
fi

bspc config border_width         4
bspc config window_gap      10

bspc config focus_follows_pointer   false
bspc config pointer_follows_focus   true
bspc config pointer_follows_monitor true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config honor_size_hints	 false
bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config normal_border_color	    \#202020
bspc config focused_border_color	\#202020
bspc config active_border_color	    \#202020
bspc config presel_feedback_color	\#202020

bspc config top_padding     -8 
bspc config bottom_padding  -8 
bspc config right_padding   0
bspc config left_padding    0

xsetroot -solid \#262626
setxkbmap -model abnt2 -layout br

polybar top -r & polybar bottom -r & 
